### ISSUE TITLE
Compilation fails on angular-cli project

### ISSUE THREAD

**Issue by ktsangop** [martincostello/applepayjs-typings#1]
First of all thanks for the effort.

I have added this package to my angular-cli project by using the following command : 
`yarn add -D @types/applepayjs`

I am using VS Code, and the intellisense picks up the types correctly, and no errors are displayed on the editor. I get the autocomplete for the provided types, and i am pointed to the index.d.ts file when i follow the type's "jump to" declaration functionality.

But when i try to build/serve using 
`ng build` or `ng serve` i get the following compilation errors : 

```
ERROR in src/app/core/services/apple-pay.service.ts(8,28): error TS2304: Cannot find name
'ApplePaySession'.
src/app/core/services/apple-pay.service.ts(9,35): error TS2503: Cannot find namespace 'ApplePayJS'.
src/app/core/services/apple-pay.service.ts(43,32): error TS2304: Cannot find name 'ApplePaySession'.
```

I have found various suggestions online, but none of them worked. I also have many other `@types` installed in my project which work fine. 

I would love any suggestions on how to overcome this.
Thanks in advance.

**Comment by martincostello** [comment]
Hi @ktsangop, unfortunately I’ve not used Angular myself, so I’m a bit stumped as it why it’s not working.

It’s supposed to be a global object, but it’s possible that maybe I mis-authored something. However these types are used over in this project https://github.com/justeat/ApplePayJSSample and it compiles and works fine.

Maybe you can compare the setup there with your own project and see if there’s a difference in the typescript configurations that make a it work?

**Comment by ktsangop** [comment]
@martincostello thanks for the response.
I will look into the sample project, and post back if i find anything.

**Comment by ktsangop** [comment]
Found this issue, and with the help of this answer, it seems that the problem is solved (?) : 
https://github.com/Microsoft/TypeScript/issues/9725#issuecomment-232629607

I have added the following import on the required Angular service: 
`import 'applepayjs';`

FWIW, i had been trying to `import` using all kinds of syntax available, apart from this one. Also, none of the rest `@types` i have in my project, require this, **but** the main difference seems to be that, the rest of the types, have also an compiled npm package that provides the implemented classes which the `@types` point to.

This is not possible with Apple Pay JS, since there is no library file you can download and import, rather than an API available only on certain devices.

**Comment by martincostello** [comment]
Cool - I’m glad you’ve gotten it working! Yeah, Apple Pay JS is more of a global browser built-in API like `console` etc., so I guess that makes some sort of difference.
