### ISSUE TITLE
Cannot reference ApplePaySession through window.ApplePaySession (TS2339)

### ISSUE THREAD

**Issue by WillHayCode** [martincostello/applepayjs-typings#3]
When I attempt to test ApplePay availability with 

```
if (window.ApplePaySession) {
    // process
}
```

TypeScript returns 

`error TS2339: Property 'ApplePaySession' does not exist on type 'Window & typeof globalThis'.`

For my use case it was enough to add

```
declare global
    interface Window {
        ApplePaySession: ApplePaySession
    }
}
```

to the top of my file, but that's not an all-inclusive solution (window.ApplePaySession.canMakePayments() throws ` error TS2576: Property 'canMakePayments' is a static member of type 'ApplePaySession'.` under this), but I thought it was worth flagging.

**Comment by martincostello** [comment]
These type definitions were subsequently copied to DefinitelyTyped/DefinitelyTyped (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15392).

If there is an issue, please submit a Pull Request and/or issue to that repository.
