### ISSUE TITLE
No ApplePayError constructor

### ISSUE THREAD

**Issue by hisham** [martincostello/applepayjs-typings#4]
See https://developer.apple.com/documentation/apple_pay_on_the_web/applepayerror

There's no type that reflects this: 

new ApplePayError("shippingContactInvalid", "postalCode", "ZIP Code is invalid")

**Comment by martincostello** [comment]
These type definitions were subsequently copied to DefinitelyTyped/DefinitelyTyped (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15392). If this type defined there doesn't meet your needs, consider submitting a Pull Request to that repository to add it:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cab98f695da81c022b0eb7957663a78e4dc64219/types/applepayjs/index.d.ts#L195-L213
